### PR TITLE
Qt 5.15.14 with OpenSSL 3.3.0 support.

### PR DESCRIPTION
**Pull request by offhub**
Qt 5.15.14 with OpenSSL 3.3.0 support.

I also resolved the issue where some patches couldn't apply to the source code due to differences in line breaks.

### CODE REVIEW

**Comment by LumitoLuma** [comment]
Thanks for your contribution. However, I have some doubts in regard to the compatibility of OpenSSL 3.x with Qt 5.15 during runtime. Have you tried SBIE with your builds? Also, I think that the build does not actually contain OpenSSL. We could compile it statically (by adding `static` to the OpenSSL configure flags) and problem solved. Otherwise, packaging of the OpenSSL build artifacts is required.

I will try to run SBIE with your builds before merging. Thanks again.

**Comment by offhub** [comment]
It is said that OpenSSL 3 support was added with Qt 5.15.13[**](https://bugreports.qt.io/browse/QTBUG-107729?focusedId=716815&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-716815). As far as I used Sandboxie (Qt.5.15.14 + OpenSSL 3) in the virtual machine, I had no problems. I have created a separate repo for OpenSSL.
https://github.com/offhub/openssl-builds/blob/main/.github/workflows/build-openssl-330.yml

**Review by LumitoLuma — APPROVED** [review]
Thanks. I've just built it and it works as expected. I'm ready to merge.

@DavidXanatos, would it be fine to move to OpenSSL 3?

**Comment by LumitoLuma** [comment]
Discussion continues here: sandboxie-plus/Sandboxie#3943.

**Pull request merged**
